export default {

  IS_LOADING: 'Lightbox/IS_LOADING',
  IS_LOADING_COMPLETE: 'Lightbox/IS_LOADING_COMPLETE',

  OPEN_LIGHTBOX: 'Lightbox/OPEN_LIGHTBOX',
  CLOSE_LIGHTBOX: 'Lightbox/CLOSE_LIGHTBOX',

  UPDATE_IMAGE_DATA: 'Lightbox/UPDATE_IMAGE_DATA',
  SAVE_IMAGE_DATA: 'Lightbox/SAVE_IMAGE_DATA',


}
