export default {

  IS_LOADING: 'Images/IS_LOADING',
  IS_LOADING_COMPLETE: 'Images/IS_LOADING_COMPLETE',

  ADD_TO_IMAGES: 'Images/ADD_TO_IMAGES',
  REMOVE_FROM_IMAGES: 'Images/REMOVE_FROM_IMAGES',

  UPDATE_IMAGE_DATA: 'Images/UPDATE_IMAGE_DATA',
  SAVE_IMAGE_DATA: 'Images/SAVE_IMAGE_DATA',

}
