export default {

  IS_LOADING: 'Images/IS_LOADING',
  IS_LOADING_COMPLETE: 'Images/IS_LOADING_COMPLETE',

  ADD_TO_LIVE: 'Images/ADD_TO_LIVE',
  REMOVE_FROM_LIVE: 'Images/REMOVE_FROM_LIVE',

  ADD_TO_UNEDITED: 'Images/ADD_TO_UNEDITED',
  REMOVE_FROM_UNEDITED: 'Images/REMOVE_FROM_UNEDITED',

  ADD_TO_HIDDEN: 'Images/ADD_TO_HIDDEN',
  REMOVE_FROM_HIDDEN: 'Images/REMOVE_FROM_HIDDEN',

}
